name: Test Student Code

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up PAT for submodule
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # Reference the PAT secret
        run: |
          git config --global url."https://github.com/"
          git submodule init
          git submodule update --recursive --remote --force

      - name: Run unit tests
        env:
          TEST_CASES_DIR: tests/test-cases-private  # Adjust this path accordingly
        run: |
          python -m unittest discover -s tests/test-cases-private
